{
 "title": "Kafka Consumer",
 "description": "spring-kafka metrics",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "application", "label": "Application", "query": "label_values(application)" },
   {
    "name": "topic",
    "label": "topic",
    "query": "label_values(kafka_consumer_fetch_manager_records_lead, topic)"
   },
   {
    "name": "client_id",
    "label": "client_id",
    "query": "label_values(kafka_consumer_fetch_manager_records_lead{topic=\"$topic\"},client_id)"
   },
   {
    "name": "instance",
    "label": "instance",
    "query": "label_values(kafka_consumer_connection_close_rate{client_id=~\"$client_id\"}, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "avg commit latency",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "avg(kafka_consumer_coordinator_commit_latency_avg{instance=~\"$instance\", client_id=~\"$client_id\"})"
    }
   ]
  },
  {
   "title": "total lag ",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(kafka_consumer_fetch_manager_records_lag{instance=~\"$instance\", client_id=~\"$client_id\", topic=~\"$topic\"})"
    }
   ]
  },
  {
   "title": "commit rate",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(kafka_consumer_coordinator_commit_rate{instance=~\"$instance\", client_id=~\"$client_id\"})"
    }
   ]
  },
  {
   "title": "join rate",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(kafka_consumer_coordinator_join_rate{instance=~\"$instance\", client_id=~\"$client_id\"})"
    }
   ]
  },
  { "title": "Fetch Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "consumption lag",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "expr": "kafka_consumer_fetch_manager_records_lag{ instance=~\"$instance\", client_id=~\"$client_id\", topic=~\"$topic\"}",
     "legendFormat": "consumer lag - {{instance}} | client-id -{{client_id}} | topic - {{topic}}"
    }
   ]
  },
  {
   "title": "consumed bytes rate",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "rate(kafka_consumer_fetch_manager_bytes_consumed_rate{ instance=~\"$instance\", client_id=~\"$client_id\", topic=~\"$topic\"}[5m])",
     "legendFormat": "consumption bytes - {{instance}} - {{client_id}} - {{topic}}"
    }
   ]
  },
  {
   "title": "fetch latency",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "kafka_consumer_fetch_manager_fetch_latency_avg{instance=~\"$instance\", client_id=~\"$client_id\"}",
     "legendFormat": "fetch avg - {{instance}} - {{client_id}}"
    },
    {
     "expr": "kafka_consumer_fetch_manager_fetch_latency_max{instance=~\"$instance\", client_id=~\"$client_id\"}",
     "legendFormat": "fetch max - {{instance}} - {{client_id}}"
    }
   ]
  },
  {
   "title": "fetch throttle",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "kafka_consumer_fetch_manager_fetch_throttle_time_avg{instance=~\"$instance\", client_id=~\"$client_id\"}",
     "legendFormat": "fetch avg - {{instance}} - {{client_id}}"
    },
    {
     "expr": "kafka_consumer_fetch_manager_fetch_throttle_time_max{instance=~\"$instance\", client_id=~\"$client_id\"}",
     "legendFormat": "fetch max - {{instance}} - {{client_id}}"
    }
   ]
  },
  {
   "title": "fetch rate",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_consumer_fetch_manager_fetch_rate{instance=~\"$instance\", client_id=~\"$client_id\"} ",
     "legendFormat": "instance - {{instance}} | client-id - {{client_id}}"
    }
   ]
  },
  {
   "title": "records per request",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 28 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "expr": "kafka_consumer_fetch_manager_records_per_request_avg{ instance=~\"$instance\", client_id=~\"$client_id\", topic=~\"$topic\"}",
     "legendFormat": "records avg - {{instance}} | client-id -{{client_id}} | topic - {{topic}}"
    }
   ]
  },
  {
   "title": "records lead",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 38 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "expr": "kafka_consumer_fetch_manager_records_lead{ instance=~\"$instance\", client_id=~\"$client_id\", topic=~\"$topic\"}",
     "legendFormat": "lead - {{instance}} | client-id -{{client_id}} | topic - {{topic}}"
    },
    {
     "expr": "kafka_consumer_fetch_manager_records_lead_min{ instance=~\"$instance\", client_id=~\"$client_id\", topic=~\"$topic\"}",
     "legendFormat": "lead min - {{instance}} | client-id -{{client_id}} | topic - {{topic}}"
    },
    {
     "expr": "kafka_consumer_fetch_manager_records_lead_avg{ instance=~\"$instance\", client_id=~\"$client_id\", topic=~\"$topic\"}",
     "legendFormat": "lead avg - {{instance}} | client-id -{{client_id}} | topic - {{topic}}"
    }
   ]
  },
  {
   "title": "Consumer Group Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 48 },
   "collapsed": true,
   "panels": [
    {
     "title": "assigned partitions",
     "type": "graph",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 49 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "kafka_consumer_coordinator_assigned_partitions{instance=~\"$instance\", client_id=~\"$client_id\"}",
       "legendFormat": "assigned - {{instance}} | client-id - {{client_id}}"
      }
     ]
    },
    {
     "title": "commit latency",
     "type": "graph",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 49 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "kafka_consumer_coordinator_commit_latency_avg{instance=~\"$instance\", client_id=~\"$client_id\"}",
       "legendFormat": "commit avg - {{instance}} | client-id - {{client_id}}"
      },
      {
       "expr": "kafka_consumer_coordinator_commit_latency_max{instance=~\"$instance\", client_id=~\"$client_id\"}",
       "legendFormat": "commit max - {{instance}} | client-id - {{client_id}}"
      }
     ]
    },
    {
     "title": "speed",
     "type": "graph",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 60 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "kafka_consumer_coordinator_commit_rate{instance=~\"$instance\", client_id=~\"$client_id\"} ",
       "legendFormat": "commit rate - {{instance}} | client-id - {{client_id}}"
      },
      {
       "expr": "kafka_consumer_coordinator_join_rate{instance=~\"$instance\", client_id=~\"$client_id\"}",
       "legendFormat": "join rate - {{instance}} | client-id - {{client_id}}"
      },
      {
       "expr": "kafka_consumer_coordinator_heartbeat_rate{instance=~\"$instance\", client_id=~\"$client_id\"} ",
       "legendFormat": "heartbeat rate - {{instance}} | client-id - {{client_id}}"
      },
      {
       "expr": "kafka_consumer_coordinator_sync_rate{instance=~\"$instance\", client_id=~\"$client_id\"} ",
       "legendFormat": "sync rate - {{instance}} | client-id - {{client_id}}"
      }
     ]
    },
    {
     "title": "join time",
     "type": "graph",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 60 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "kafka_consumer_coordinator_join_time_avg{instance=~\"$instance\", client_id=~\"$client_id\"}",
       "legendFormat": "join avg - {{instance}} | client-id - {{client_id}}"
      },
      {
       "expr": "kafka_consumer_coordinator_join_time_max{instance=~\"$instance\", client_id=~\"$client_id\"}\n",
       "legendFormat": "join max - {{instance}} | client-id - {{client_id}}"
      }
     ]
    },
    {
     "title": "last heartbeat ago",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 71 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "kafka_consumer_coordinator_last_heartbeat_seconds_ago{ instance=~\"$instance\", client_id=~\"$client_id\"} ",
       "legendFormat": "heartbeat ago - {{instance}} | client-id - {{client_id}}"
      }
     ]
    },
    {
     "title": "sync time",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 71 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "kafka_consumer_coordinator_sync_time_avg{instance=~\"$instance\", client_id=~\"$client_id\"}",
       "legendFormat": "sync avg - {{instance}} | client-id - {{client_id}}"
      },
      {
       "expr": "kafka_consumer_coordinator_sync_time_max{instance=~\"$instance\", client_id=~\"$client_id\"}",
       "legendFormat": "sync max - {{instance}} | client-id - {{client_id}}"
      }
     ]
    },
    {
     "title": "rebalance latency ",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 80 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "kafka_consumer_coordinator_rebalance_latency_avg{instance=~\"$instance\", client_id=~\"$client_id\"}",
       "legendFormat": "rebalance avg - {{instance}} | client-id - {{client_id}}"
      },
      {
       "expr": "kafka_consumer_coordinator_rebalance_latency_max{instance=~\"$instance\", client_id=~\"$client_id\"}",
       "legendFormat": "rebalance max - {{instance}} | client-id - {{client_id}}"
      }
     ]
    },
    {
     "title": "rebalance total ",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 80 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "kafka_consumer_coordinator_rebalance_total{instance=~\"$instance\", client_id=~\"$client_id\"}",
       "legendFormat": "rebalance total - {{instance}} | client-id - {{client_id}}"
      },
      {
       "expr": "kafka_consumer_coordinator_failed_rebalance_total{instance=~\"$instance\", client_id=~\"$client_id\"}",
       "legendFormat": "rebalance failed total - {{instance}} | client-id - {{client_id}}"
      }
     ]
    },
    {
     "title": "rebalance rate per hour",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 89 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "kafka_consumer_coordinator_rebalance_rate_per_hour{instance=~\"$instance\", client_id=~\"$client_id\"}",
       "legendFormat": "rebalance per hour - {{instance}} | client-id - {{client_id}}"
      },
      {
       "expr": "kafka_consumer_coordinator_failed_rebalance_rate_per_hour{instance=~\"$instance\", client_id=~\"$client_id\"}",
       "legendFormat": "rebalance failed per - {{instance}} | client-id - {{client_id}}"
      }
     ]
    },
    {
     "title": "last rebalance ago",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 89 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "kafka_consumer_coordinator_last_rebalance_seconds_ago{instance=~\"$instance\", client_id=~\"$client_id\"}",
       "legendFormat": "last rebalance - {{instance}} | client-id - {{client_id}}"
      }
     ]
    },
    {
     "title": "partition assigned / revoked latency",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 98 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "kafka_consumer_coordinator_partition_assigned_latency_avg{instance=~\"$instance\", client_id=~\"$client_id\"}",
       "legendFormat": "assigned avg - {{instance}} | client-id - {{client_id}}"
      },
      {
       "expr": "kafka_consumer_coordinator_partition_revoked_latency_avg{instance=~\"$instance\", client_id=~\"$client_id\"}",
       "legendFormat": "revoked avg - {{instance}} | client-id - {{client_id}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Global Connection Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 49 },
   "collapsed": true,
   "panels": [
    {
     "title": "number of connections",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 108 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "kafka_consumer_connection_count_total{instance=~\"$instance\", client_id=~\"$client_id\"}",
       "legendFormat": "connection total - {{instance}} | client-id - {{client_id}}"
      },
      {
       "expr": "kafka_consumer_connection_creation_total{application=~\"$application\", instance=\"$instance\", client_id=~\"$client_id\"}",
       "legendFormat": "connetion create - {{instance}} | client-id - {{client_id}}"
      },
      {
       "expr": "kafka_consumer_connection_close_total{application=~\"$application\", instance=\"$instance\", client_id=~\"$client_id\"}",
       "legendFormat": "connection close - {{instance}} | client-id - {{client_id}}"
      }
     ]
    },
    {
     "title": "io ratio",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 108 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "kafka_consumer_io_ratio{instance=~\"$instance\", client_id=~\"$client_id\"}",
       "legendFormat": "io ratio - {{instance}} | client-id - {{client_id}}"
      }
     ]
    },
    {
     "title": "io wait ratio",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 118 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "kafka_consumer_io_wait_ratio{instance=~\"$instance\", client_id=~\"$client_id\"}",
       "legendFormat": "io wair ratio - {{instance}} | client-id - {{client_id}}"
      }
     ]
    },
    {
     "title": "io wait time",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 118 },
     "yaxes": [
      { "format": "ns" }
     ],
     "targets": [
      {
       "expr": "kafka_consumer_io_wait_time_ns_avg{instance=~\"$instance\", client_id=~\"$client_id\"}",
       "legendFormat": "io wait time  - {{instance}} | client-id - {{client_id}}"
      }
     ]
    },
    {
     "title": "io time",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 128 },
     "yaxes": [
      { "format": "ns" }
     ],
     "targets": [
      {
       "expr": "kafka_consumer_io_time_ns_avg{instance=~\"$instance\", client_id=~\"$client_id\"}",
       "legendFormat": "io time  - {{instance}} | client-id - {{client_id}}"
      }
     ]
    },
    {
     "title": "select rate",
     "type": "graph",
     "description": "Number of times the I/O layer checked for new I/O to perform per second.\n",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 128 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "kafka_consumer_select_rate{instance=~\"$instance\", client_id=~\"$client_id\"}",
       "legendFormat": "select rate  - {{instance}} | client-id - {{client_id}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Per-Broker Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 50 },
   "collapsed": true,
   "panels": [
    {
     "title": "incoming / outgoing bytes rate",
     "type": "graph",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 109 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "kafka_consumer_incoming_byte_rate{ instance=~\"$instance\", client_id=~\"$client_id\"}",
       "legendFormat": "incoming - {{instance}} | client-id - {{client_id}} - {{topic}}"
      },
      {
       "expr": "kafka_consumer_outgoing_byte_rate{instance=~\"$instance\", client_id=~\"$client_id\"}",
       "legendFormat": "outgoing - {{instance}} | client-id - {{client_id}}"
      }
     ]
    },
    {
     "title": "request size",
     "type": "graph",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 109 },
     "yaxes": [
      { "format": "locale" }
     ],
     "targets": [
      {
       "expr": "kafka_consumer_request_size_avg{ instance=~\"$instance\", client_id=~\"$client_id\"}",
       "legendFormat": "request avg - {{instance}} | client-id - {{client_id}} - {{topic}}"
      },
      {
       "expr": "kafka_consumer_request_size_max{instance=~\"$instance\", client_id=~\"$client_id\"}",
       "legendFormat": "request max - {{instance}} | client-id - {{client_id}}"
      }
     ]
    },
    {
     "title": "request / response",
     "type": "graph",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 120 },
     "yaxes": [
      { "format": "locale" }
     ],
     "targets": [
      {
       "expr": "kafka_consumer_node_request_rate{ instance=~\"$instance\", client_id=~\"$client_id\"}",
       "legendFormat": "request rate - {{instance}} | client-id - {{client_id}} | node {{node_id}}"
      },
      {
       "expr": "kafka_consumer_node_response_rate{instance=~\"$instance\", client_id=~\"$client_id\"}",
       "legendFormat": "response rate - {{instance}} | client-id - {{client_id}} | node {{node_id}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Poll metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 51 },
   "collapsed": true,
   "panels": [
    {
     "title": "time between poll ",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 52 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "kafka_consumer_time_between_poll_avg{ instance=~\"$instance\", client_id=~\"$client_id\"}",
       "legendFormat": "time between poll avg {{instance}}"
      },
      {
       "expr": "kafka_consumer_time_between_poll_max{ instance=~\"$instance\", client_id=~\"$client_id\"}",
       "legendFormat": "time between poll max {{instance}}"
      }
     ]
    },
    {
     "title": "Last poll ago",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 52 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "kafka_consumer_last_poll_seconds_ago{ instance=~\"$instance\", client_id=~\"$client_id\"}",
       "legendFormat": "last poll ago {{instance}}"
      }
     ]
    },
    {
     "title": "poll idle time",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 60 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "kafka_consumer_poll_idle_ratio_avg{ instance=~\"$instance\", client_id=~\"$client_id\"}",
       "legendFormat": "time idle {{instance}}"
      }
     ]
    }
   ]
  }
 ]
}